name: Compatibility CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {contao: '^5.7', php: '8.2', dependencies: lowest}
          - {contao: '^5.7', php: '8.3', dependencies: highest}
          - {contao: '^6.0', php: '8.3', dependencies: lowest}
          - {contao: '^6.0', php: '8.4', dependencies: highest}
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: {php-version: '${{ matrix.php }}', coverage: none}
      - run: composer require --no-update contao/core-bundle:${{ matrix.contao }}
      - run: composer update --prefer-dist --no-interaction ${{ matrix.dependencies == 'lowest' && '--prefer-lowest' || '' }}
      - run: find src contao tests -name '*.php' -print0 | xargs -0 -n1 php -l
      - run: composer test
      - run: composer analyse
